server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    location = /flutter_service_worker.js {
        add_header Cache-Control "no-cache";
    }

    location = /version.json {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types
        application/javascript
        application/json
        application/wasm
        image/svg+xml
        text/css
        text/plain;
}
