name: Gh-Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.44.6'
          cache: true
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /portfolio_flutter_web/
